version: '2'
services:
  mysql:
    build: ./services/mysql
    ports:
      - 3306:3306
    restart: always
    env_file:
      - ./services/mysql/mysql.env
    volumes:
        - /Users/pongnianvictor/database/mysql:/var/lib/mysql

  superset:
    build: ./services/superset
    ports:
      - 8088:8088
    volumes:
        - /Users/pongnianvictor/superset:/var/lib/superset
