-- @NOTE: @Nezar This is Postgres configuration file. Maybe there's some relevant settings to use alongside our mysql instance.

-- SET statement_timeout = 0;
-- SET lock_timeout = 0;
-- SET client_encoding = 'UTF8';
-- SET standard_conforming_strings = on;
-- SET check_function_bodies = false;
-- SET client_min_messages = warning;
-- SET row_security = off;
--
-- SET search_path = public, pg_catalog;
--
-- DROP EXTENSION plpgsql;
-- DROP SCHEMA public;
--
-- CREATE SCHEMA public;
--
--
-- ALTER SCHEMA public OWNER TO postgres;
--
-- COMMENT ON SCHEMA public IS 'standard public schema';
--
-- CREATE EXTENSION IF NOT EXISTS plpgsql WITH SCHEMA pg_catalog;
--
-- COMMENT ON EXTENSION plpgsql IS 'PL/pgSQL procedural language';
--
-- SET search_path = public, pg_catalog;
--
-- SET default_tablespace = '';
--
-- SET default_with_oids = false;

CREATE DATABASE juckerfarm_data;
